package io.lonmstalker.telegrambots.constants

object TelegramApiConstants {
    const val CHAT_ID = "chat_id"
    const val REPLY_MARKUP = "reply_markup"
    const val REPLY_TO_MESSAGE_ID = "reply_to_message_id"
    const val MESSAGE_THREAD_ID = "message_thread_id"
    const val CAPTION = "caption"
    const val PARSE_MODE = "parse_mode"
    const val DISABLE_NOTIFICATION = "disable_notification"
    const val DISABLE_CONTENT_TYPE_DETECTION = "disable_content_type_detection"
    const val ALLOW_SENDING_WITHOUT_REPLY = "allow_sending_without_reply"
    const val PROTECT_CONTENT = "protect_content"
    const val CAPTION_ENTITIES = "caption_entities"
    const val HAS_SPOILER = "has_spoiler"
    const val SUPPORTS_STREAMING = "supports_streaming"
    const val DURATION = "duration"
    const val WIDTH = "width"
    const val HEIGHT = "height"
    const val THUMB = "thumb"
    const val LENGTH = "length"
    const val PERFORMER = "performer"
    const val TITLE = "title"
    const val USER_ID = "user_id"
    const val NAME = "name"
    const val EMOJIS = "emojis"
    const val MASK_POSITION = "mask_position"
    const val STICKER_TYPE = "sticker_type"
    const val PNG_STICKER = "png_sticker"
    const val TGS_STICKER = "tgs_sticker"
    const val WEBM_STICKER = "webm_sticker"
    const val MESSAGE_ID = "message_id"
    const val INLINE_MESSAGE_ID = "inline_message_id"
    const val ANIMATION = "animation"
    const val URL = "url"
    const val MAX_CONNECTIONS = "max_connections"
    const val ALLOWED_UPDATES = "allowed_updates"
    const val IP_ADDRESS = "ip_address"
    const val DROP_PENDING_UPDATES = "drop_pending_updates"
    const val SECRET_TOKEN = "secret_token"
    const val CERTIFICATE = "certificate"
    const val CALLBACK = "callback"
}